# Selecting Python version
FROM python:3.11-slim

# Setting environment variables to non-interactive, this makes sure
# that apt-get does not wait for user input during execution
ENV DEBIAN_FRONTEND=noninteractive

# Installing Linux libraries and default g++ (which should support C++11)
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    python3-dev \
    libxml2 \
    libpq-dev \
    libblas3 \
    liblapack3 \
    liblapack-dev \
    gfortran \
    libatlas-base-dev


# Upgrade pip to the latest version
RUN pip install --upgrade pip

# Copying requirements for python packages and installing them
WORKDIR /app
COPY env_spec/requirements.txt /app/env_spec/requirements.txt
RUN pip install --no-cache-dir -r env_spec/requirements.txt

# Copy the models.txt file into the container
COPY env_spec/embedding_models.txt /app/env_spec/embedding_models.txt

# Download the Sentence Transformer models listed in models.txt
RUN python -c "from sentence_transformers import SentenceTransformer; [SentenceTransformer(model.strip()) for model in open('/app/env_spec/embedding_models.txt').readlines()]"
