# Collect latest image from docker registry
FROM kyriosskia/mocker-db-dependancies:latest

# Upgrade to the latest version of mockerdb
RUN pip install --upgrade pip
RUN pip install mocker-db


# Copy and select as working directory files from pulled docker image
COPY . /app
WORKDIR /app

# Making port 80 available outside of the container
EXPOSE 8080

# Command to run the Uvicorn server
CMD ["uvicorn", "main:app" , "--host", "0.0.0.0", "--port", "8080"]