# Collect latest image from docker registry
FROM kyriosskia/mocker-db-dependacies:latest

# Copy and select as working directory files from pulled docker image
COPY . /app
WORKDIR /app

# Command to run the Uvicorn server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]