# Selecting Python version
FROM python:3.11-slim as builder

# Setting environment variables to non-interactive, this makes sure
# that apt-get does not wait for user input during execution
ENV DEBIAN_FRONTEND=noninteractive

# Installing Linux libraries and default g++ (which should support C++11)
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    python3-dev \
    libxml2 \
    libpq-dev \
    libblas3 \
    liblapack3 \
    liblapack-dev \
    gfortran \
    libatlas-base-dev


# Upgrade pip to the latest version
RUN pip install --upgrade pip

# Copying requirements for python packages and installing them
WORKDIR /app
COPY env_spec/requirements.txt /app/env_spec/requirements.txt
RUN pip install -r env_spec/requirements.txt
