name: Docker Dependencies Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_docker_base.yml
      - env_spec/requirements.txt
      - env_spec/Dockerfile_build

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t kyriosskia/mocker-db-dependancies -f env_spec/Dockerfile_base .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push kyriosskia/mocker-db-dependacies:latest
