name: Docker Dependencies Build and Push

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build_docker_base.yml
      - env_spec/requirements.txt
      - env_spec/Dockerfile_build

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ github.workspace }}/env_spec/Dockerfile_base
          push: true
          tags: kyriosskia/mocker-db-dependancies:latest