name: Docker MockerDB Build and Push

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - main.py
      - utils/*
      - conf/mocker_setup_params.yaml
      - conf/settings.py
      - env_spec/Dockerfile_run

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11

        - name: Update API version
          run: |
            pip install mocker-db

            chmod +x tools/get_update_package_version.sh
            chmod +x tools/update_api_version.sh

            ./tools/get_update_package_version.sh
            ./tools/update_api_version.sh

        - name: Add and push tag
          run: |
            chmod +x tools/make_and_push_tag.sh

            ./tools/update_api_version.sh

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build and Push
          uses: docker/build-push-action@v2
          with:
            context: .
            file: ${{ github.workspace }}/env_spec/Dockerfile_run
            push: true
            tags: kyriosskia/mocker-db:latest






