name: Generate API Documentation

on:
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r env_spec/requirements.txt
        pip install mocker-db
        pip install package-auto-assembler

    - name: Update API version
      run: |
        chmod +x .github/tools/get_update_package_version.sh
        chmod +x .github/tools/update_api_version.sh

        .github/tools/get_update_package_version.sh
        .github/tools/update_api_version.sh

    - name: Start FastAPI server
      run: |
        paa run-api-routes --package mocker-db --host 0.0.0.0 --port 8000 &
        echo "Waiting for FastAPI to launch on port 8000..."
        while ! nc -z localhost 8000; do
          sleep 1
        done
        echo "FastAPI server is up and running!"

    - name: Fetch OpenAPI JSON
      run: |
        curl http://localhost:8000/openapi.json -o openapi.json

    - name: Generate Markdown and update README
      run: |
        chmod +x .github/tools/update_readme.sh
        .github/tools/update_readme.sh

    - name: Commit and push README, tag
      run: |
        chmod +x .github/tools/make_and_push_tag.sh

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin HEAD:main

        git add README.md docs/API_ENDPOINTS.md

        .github/tools/make_and_push_tag.sh

    - name: Update docker image description
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_HUB_REPOSITORY: "mocker-db"
      run: |
        chmod +x .github/tools/update_docker_hub_description.sh
        .github/tools/update_docker_hub_description.sh "$DOCKER_HUB_USERNAME" "$DOCKER_HUB_PASSWORD" "$DOCKER_HUB_REPOSITORY"

