name: Generate API Documentation

on:
  push:
    branches:
      - main

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn[standard] httpx

    - name: Update API version
      run: |
        pip install mocker-db

        chmod +x tools/get_update_package_version.sh
        chmod +x tools/update_api_version.sh

        ./tools/get_update_package_version.sh
        ./tools/update_api_version.sh

    - name: Start FastAPI server
      run: uvicorn main:app --port 8000

    - name: Fetch OpenAPI JSON
      run: |
        sleep 10  # give FastAPI server time to start
        curl http://localhost:8000/openapi.json -o openapi.json

    - name: Generate Markdown and update README
      run: |
        chmod +x tools/update_readme.sh
        python tools/update_readme.sh

    - name: Commit and push README, tag
      run: |
        chmod +x tools/make_and_push_tag.sh

        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git pull origin HEAD:main

        git add README.md docs/API_ENDPOINTS.md

        ./tools/make_and_push_tag.sh

